/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bicerproject;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Scanner;
import javax.swing.JOptionPane;
import java.util.Random;

/**
 *
 * @author User
 */
public class adminPage extends javax.swing.JFrame {

    /**
     * Creates new form adminPage
     */
    public adminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPage_OpenExams = new javax.swing.JButton();
        adminPage_ControlDB = new javax.swing.JButton();
        adminPage_DisplayDB = new javax.swing.JButton();
        AdminPage_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminPage_OpenExams.setText("Open Exams");
        adminPage_OpenExams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPage_OpenExamsActionPerformed(evt);
            }
        });

        adminPage_ControlDB.setText("Control DATABASE");
        adminPage_ControlDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPage_ControlDBActionPerformed(evt);
            }
        });

        adminPage_DisplayDB.setText("DISPLAY STUDENTS");
        adminPage_DisplayDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPage_DisplayDBActionPerformed(evt);
            }
        });

        AdminPage_Exit.setText("EXIT");
        AdminPage_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPage_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminPage_Exit)
                    .addComponent(adminPage_DisplayDB)
                    .addComponent(adminPage_ControlDB)
                    .addComponent(adminPage_OpenExams))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(adminPage_OpenExams)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminPage_ControlDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminPage_DisplayDB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminPage_Exit)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminPage_OpenExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPage_OpenExamsActionPerformed
        new makeExamScreen().setVisible(true);
    }//GEN-LAST:event_adminPage_OpenExamsActionPerformed

    private void adminPage_DisplayDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPage_DisplayDBActionPerformed
      String listOfStudent = "";
        for(int i = 0; i < readStudentDataBase().size(); i++)
        {
            listOfStudent += (i+1) + "-" +readStudentDataBase().get(i) + "\n";
        }
        JOptionPane.showMessageDialog(null,listOfStudent);
    }//GEN-LAST:event_adminPage_DisplayDBActionPerformed

    private void adminPage_ControlDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPage_ControlDBActionPerformed
       Random generate = new Random();
       int ping = generate.nextInt(100)+10;
       JOptionPane.showMessageDialog(null,"Ping = " + ping + "ms");
    }//GEN-LAST:event_adminPage_ControlDBActionPerformed

    private void AdminPage_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPage_ExitActionPerformed
        new Login().setVisible(true);
    }//GEN-LAST:event_AdminPage_ExitActionPerformed

    public static ArrayList<String> readStudentDataBase() //sifreli mailleri cozerek maillere ulasir bunu da arrayliste gomer
    {
        String path = Database.getStudentDatabase();
        BufferedReader br = null;
        FileReader fr = null;
        ArrayList<String> listOfStudentEmail = new ArrayList<String>();

        try {
            fr = new FileReader(path);
            br = new BufferedReader(fr);

            String currentLine;

            while ((currentLine = br.readLine()) != null) {
                int spaceIndex = currentLine.indexOf(" ");
                listOfStudentEmail.add(currentLine.substring(0, spaceIndex));//sifreli emailleri arrayliste attik
            }

            for (int i = 0; i < listOfStudentEmail.size(); i++) {
                String encodedMail = listOfStudentEmail.get(i);
                String decodedMail = new String(Base64.getDecoder().decode(encodedMail.getBytes()));
                listOfStudentEmail.set(i, decodedMail);
            }
           
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

        return listOfStudentEmail;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminPage_Exit;
    private javax.swing.JButton adminPage_ControlDB;
    private javax.swing.JButton adminPage_DisplayDB;
    private javax.swing.JButton adminPage_OpenExams;
    // End of variables declaration//GEN-END:variables
}
