/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bicerproject;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.io.File;
import javax.swing.JOptionPane;

public class studentPage extends javax.swing.JFrame {

    /**
     * Creates new form studentPage
     */
    public studentPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentPage_DisplayExam = new javax.swing.JButton();
        studentPage_DisplayResult = new javax.swing.JButton();
        studentPage_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentPage_DisplayExam.setText("DISPLAY EXAM");
        studentPage_DisplayExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentPage_DisplayExamActionPerformed(evt);
            }
        });

        studentPage_DisplayResult.setText("DISPLAY EXAM RESULTS");

        studentPage_exit.setText("EXIT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentPage_DisplayResult)
                    .addComponent(studentPage_DisplayExam)
                    .addComponent(studentPage_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(studentPage_DisplayExam)
                .addGap(29, 29, 29)
                .addComponent(studentPage_DisplayResult)
                .addGap(40, 40, 40)
                .addComponent(studentPage_exit)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentPage_DisplayExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentPage_DisplayExamActionPerformed
        checkTheExamListDatabase();
    }//GEN-LAST:event_studentPage_DisplayExamActionPerformed

    public static void checkTheExamListDatabase() {
        try {
            System.out.println("THE EXAM LIST");
            FileReader fr = new FileReader(Database.getExamList());
            BufferedReader br = new BufferedReader(fr);
            ArrayList<String> examList = new ArrayList<String>();
            int choice;
            String sCurrentLine;

            while ((sCurrentLine = br.readLine()) != null) {

                System.out.println(sCurrentLine);
                sCurrentLine = sCurrentLine.substring(sCurrentLine.indexOf("-") + 2, sCurrentLine.length()) + ".txt";
                examList.add(sCurrentLine);
            }

            fr.close();
            br.close();

            System.out.println("Select the exam");
            Scanner sc = new Scanner(System.in);
            choice = sc.nextInt();
            startTheExam(choice, examList);

        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    public static void startTheExam(int choice, ArrayList<String> list) throws Exception {
        File dir = new File("C:\\Users\\User\\Documents\\NetBeansProjects\\BicerProject\\Exam");
        String exam = "C:\\Users\\User\\Documents\\NetBeansProjects\\BicerProject\\Exam\\" + list.get(choice - 1);
        File files[] = dir.listFiles();
        String examStream = "";

        for (int i = 0; i < files.length; i++) {
            if (exam.equalsIgnoreCase(files[i].getAbsolutePath())) {
                FileReader fr = new FileReader(exam);
                BufferedReader br = new BufferedReader(fr);
                String s;
                while ((s = br.readLine()) != null) {
                    examStream = s;
                }
                br.close();
                JOptionPane.showMessageDialog(null,examStream);
            }
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton studentPage_DisplayExam;
    private javax.swing.JButton studentPage_DisplayResult;
    private javax.swing.JButton studentPage_exit;
    // End of variables declaration//GEN-END:variables
}
